# Generated by Django 3.1.3 on 2020-11-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lab',
            name='college_lab',
        ),
        migrations.AddConstraint(
            model_name='lab',
            constraint=models.UniqueConstraint(fields=('lab_id', 'college_dept'), name='college_lab'),
        ),
    ]
